-- Désactiver FK temporairement pour finaliser l'import
ALTER TABLE sale_items DISABLE TRIGGER ALL;
ALTER TABLE purchase_items DISABLE TRIGGER ALL;
ALTER TABLE supplier_return_items DISABLE TRIGGER ALL;
ALTER TABLE web_order_items DISABLE TRIGGER ALL;
ALTER TABLE stock_operations DISABLE TRIGGER ALL;
ALTER TABLE products DISABLE TRIGGER ALL;
ALTER TABLE sales DISABLE TRIGGER ALL;
ALTER TABLE purchases DISABLE TRIGGER ALL;
ALTER TABLE supplier_returns DISABLE TRIGGER ALL;
ALTER TABLE web_orders DISABLE TRIGGER ALL;
ALTER TABLE fridge_sales DISABLE TRIGGER ALL;
ALTER TABLE customer_payments DISABLE TRIGGER ALL;
